port: "8081"
executor_url: "http://localhost:8082/deals"
http_client_timeout: 2s
fees:
  Binance: 0.0001
  Bybit: 0.0001
  OKX: 0.0001
  Coinbase: 0.004

# # real fees:
# fees:
#   Binance: 0.001
#   Bybit: 0.001
#   OKX: 0.001
#   Coinbase: 0.004
