// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: contracts/service.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoinName int32

const (
	CoinName_COIN_UNSPECIFIED CoinName = 0
	CoinName_COIN_BTC         CoinName = 1
	CoinName_COIN_ETH         CoinName = 2
	CoinName_COIN_XAUT        CoinName = 3
)

// Enum value maps for CoinName.
var (
	CoinName_name = map[int32]string{
		0: "COIN_UNSPECIFIED",
		1: "COIN_BTC",
		2: "COIN_ETH",
		3: "COIN_XAUT",
	}
	CoinName_value = map[string]int32{
		"COIN_UNSPECIFIED": 0,
		"COIN_BTC":         1,
		"COIN_ETH":         2,
		"COIN_XAUT":        3,
	}
)

func (x CoinName) Enum() *CoinName {
	p := new(CoinName)
	*p = x
	return p
}

func (x CoinName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoinName) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_service_proto_enumTypes[0].Descriptor()
}

func (CoinName) Type() protoreflect.EnumType {
	return &file_contracts_service_proto_enumTypes[0]
}

func (x CoinName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoinName.Descriptor instead.
func (CoinName) EnumDescriptor() ([]byte, []int) {
	return file_contracts_service_proto_rawDescGZIP(), []int{0}
}

type ExchangeName int32

const (
	ExchangeName_EXCHANGE_UNSPECIFIED ExchangeName = 0
	ExchangeName_EXCHANGE_BINANCE     ExchangeName = 1
	ExchangeName_EXCHANGE_BITGET      ExchangeName = 2
	ExchangeName_EXCHANGE_BYBIT       ExchangeName = 3
	ExchangeName_EXCHANGE_OKX         ExchangeName = 5
)

// Enum value maps for ExchangeName.
var (
	ExchangeName_name = map[int32]string{
		0: "EXCHANGE_UNSPECIFIED",
		1: "EXCHANGE_BINANCE",
		2: "EXCHANGE_BITGET",
		3: "EXCHANGE_BYBIT",
		5: "EXCHANGE_OKX",
	}
	ExchangeName_value = map[string]int32{
		"EXCHANGE_UNSPECIFIED": 0,
		"EXCHANGE_BINANCE":     1,
		"EXCHANGE_BITGET":      2,
		"EXCHANGE_BYBIT":       3,
		"EXCHANGE_OKX":         5,
	}
)

func (x ExchangeName) Enum() *ExchangeName {
	p := new(ExchangeName)
	*p = x
	return p
}

func (x ExchangeName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExchangeName) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_service_proto_enumTypes[1].Descriptor()
}

func (ExchangeName) Type() protoreflect.EnumType {
	return &file_contracts_service_proto_enumTypes[1]
}

func (x ExchangeName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExchangeName.Descriptor instead.
func (ExchangeName) EnumDescriptor() ([]byte, []int) {
	return file_contracts_service_proto_rawDescGZIP(), []int{1}
}

type BidAsk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           float64                `protobuf:"fixed64,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           float64                `protobuf:"fixed64,2,opt,name=ask,proto3" json:"ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAsk) Reset() {
	*x = BidAsk{}
	mi := &file_contracts_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAsk) ProtoMessage() {}

func (x *BidAsk) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAsk.ProtoReflect.Descriptor instead.
func (*BidAsk) Descriptor() ([]byte, []int) {
	return file_contracts_service_proto_rawDescGZIP(), []int{0}
}

func (x *BidAsk) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *BidAsk) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

type MarketTickerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinName      CoinName               `protobuf:"varint,1,opt,name=coin_name,json=coinName,proto3,enum=contracts.CoinName" json:"coin_name,omitempty"`
	ExchangeName  ExchangeName           `protobuf:"varint,2,opt,name=exchange_name,json=exchangeName,proto3,enum=contracts.ExchangeName" json:"exchange_name,omitempty"`
	Price         *BidAsk                `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketTickerInfo) Reset() {
	*x = MarketTickerInfo{}
	mi := &file_contracts_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketTickerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTickerInfo) ProtoMessage() {}

func (x *MarketTickerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTickerInfo.ProtoReflect.Descriptor instead.
func (*MarketTickerInfo) Descriptor() ([]byte, []int) {
	return file_contracts_service_proto_rawDescGZIP(), []int{1}
}

func (x *MarketTickerInfo) GetCoinName() CoinName {
	if x != nil {
		return x.CoinName
	}
	return CoinName_COIN_UNSPECIFIED
}

func (x *MarketTickerInfo) GetExchangeName() ExchangeName {
	if x != nil {
		return x.ExchangeName
	}
	return ExchangeName_EXCHANGE_UNSPECIFIED
}

func (x *MarketTickerInfo) GetPrice() *BidAsk {
	if x != nil {
		return x.Price
	}
	return nil
}

type ProfitDealInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinName      CoinName               `protobuf:"varint,1,opt,name=coin_name,json=coinName,proto3,enum=contracts.CoinName" json:"coin_name,omitempty"`
	AskExchange   ExchangeName           `protobuf:"varint,2,opt,name=ask_exchange,json=askExchange,proto3,enum=contracts.ExchangeName" json:"ask_exchange,omitempty"`
	BidExchange   ExchangeName           `protobuf:"varint,3,opt,name=bid_exchange,json=bidExchange,proto3,enum=contracts.ExchangeName" json:"bid_exchange,omitempty"`
	AskPrice      float64                `protobuf:"fixed64,4,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	BidPrice      float64                `protobuf:"fixed64,5,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	ProfitAbs     float64                `protobuf:"fixed64,6,opt,name=profit_abs,json=profitAbs,proto3" json:"profit_abs,omitempty"`
	ProfitPercent float64                `protobuf:"fixed64,7,opt,name=profit_percent,json=profitPercent,proto3" json:"profit_percent,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfitDealInfo) Reset() {
	*x = ProfitDealInfo{}
	mi := &file_contracts_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitDealInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitDealInfo) ProtoMessage() {}

func (x *ProfitDealInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitDealInfo.ProtoReflect.Descriptor instead.
func (*ProfitDealInfo) Descriptor() ([]byte, []int) {
	return file_contracts_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProfitDealInfo) GetCoinName() CoinName {
	if x != nil {
		return x.CoinName
	}
	return CoinName_COIN_UNSPECIFIED
}

func (x *ProfitDealInfo) GetAskExchange() ExchangeName {
	if x != nil {
		return x.AskExchange
	}
	return ExchangeName_EXCHANGE_UNSPECIFIED
}

func (x *ProfitDealInfo) GetBidExchange() ExchangeName {
	if x != nil {
		return x.BidExchange
	}
	return ExchangeName_EXCHANGE_UNSPECIFIED
}

func (x *ProfitDealInfo) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

func (x *ProfitDealInfo) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *ProfitDealInfo) GetProfitAbs() float64 {
	if x != nil {
		return x.ProfitAbs
	}
	return 0
}

func (x *ProfitDealInfo) GetProfitPercent() float64 {
	if x != nil {
		return x.ProfitPercent
	}
	return 0
}

func (x *ProfitDealInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RecentDeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	BuyExchange   string                 `protobuf:"bytes,2,opt,name=buy_exchange,json=buyExchange,proto3" json:"buy_exchange,omitempty"`
	SellExchange  string                 `protobuf:"bytes,3,opt,name=sell_exchange,json=sellExchange,proto3" json:"sell_exchange,omitempty"`
	ProfitPercent float64                `protobuf:"fixed64,4,opt,name=profit_percent,json=profitPercent,proto3" json:"profit_percent,omitempty"`
	EarnedUsd     float64                `protobuf:"fixed64,5,opt,name=earned_usd,json=earnedUsd,proto3" json:"earned_usd,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentDeal) Reset() {
	*x = RecentDeal{}
	mi := &file_contracts_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentDeal) ProtoMessage() {}

func (x *RecentDeal) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentDeal.ProtoReflect.Descriptor instead.
func (*RecentDeal) Descriptor() ([]byte, []int) {
	return file_contracts_service_proto_rawDescGZIP(), []int{3}
}

func (x *RecentDeal) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *RecentDeal) GetBuyExchange() string {
	if x != nil {
		return x.BuyExchange
	}
	return ""
}

func (x *RecentDeal) GetSellExchange() string {
	if x != nil {
		return x.SellExchange
	}
	return ""
}

func (x *RecentDeal) GetProfitPercent() float64 {
	if x != nil {
		return x.ProfitPercent
	}
	return 0
}

func (x *RecentDeal) GetEarnedUsd() float64 {
	if x != nil {
		return x.EarnedUsd
	}
	return 0
}

func (x *RecentDeal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DealStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentBalance float64                `protobuf:"fixed64,1,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	TotalEarned    float64                `protobuf:"fixed64,2,opt,name=total_earned,json=totalEarned,proto3" json:"total_earned,omitempty"`
	DealsCount     int64                  `protobuf:"varint,3,opt,name=deals_count,json=dealsCount,proto3" json:"deals_count,omitempty"`
	RecentDeals    []*RecentDeal          `protobuf:"bytes,4,rep,name=recent_deals,json=recentDeals,proto3" json:"recent_deals,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DealStats) Reset() {
	*x = DealStats{}
	mi := &file_contracts_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealStats) ProtoMessage() {}

func (x *DealStats) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealStats.ProtoReflect.Descriptor instead.
func (*DealStats) Descriptor() ([]byte, []int) {
	return file_contracts_service_proto_rawDescGZIP(), []int{4}
}

func (x *DealStats) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *DealStats) GetTotalEarned() float64 {
	if x != nil {
		return x.TotalEarned
	}
	return 0
}

func (x *DealStats) GetDealsCount() int64 {
	if x != nil {
		return x.DealsCount
	}
	return 0
}

func (x *DealStats) GetRecentDeals() []*RecentDeal {
	if x != nil {
		return x.RecentDeals
	}
	return nil
}

var File_contracts_service_proto protoreflect.FileDescriptor

const file_contracts_service_proto_rawDesc = "" +
	"\n" +
	"\x17contracts/service.proto\x12\tcontracts\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x06BidAsk\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x02 \x01(\x01R\x03ask\"\xab\x01\n" +
	"\x10MarketTickerInfo\x120\n" +
	"\tcoin_name\x18\x01 \x01(\x0e2\x13.contracts.CoinNameR\bcoinName\x12<\n" +
	"\rexchange_name\x18\x02 \x01(\x0e2\x17.contracts.ExchangeNameR\fexchangeName\x12'\n" +
	"\x05price\x18\x03 \x01(\v2\x11.contracts.BidAskR\x05price\"\xf4\x02\n" +
	"\x0eProfitDealInfo\x120\n" +
	"\tcoin_name\x18\x01 \x01(\x0e2\x13.contracts.CoinNameR\bcoinName\x12:\n" +
	"\fask_exchange\x18\x02 \x01(\x0e2\x17.contracts.ExchangeNameR\vaskExchange\x12:\n" +
	"\fbid_exchange\x18\x03 \x01(\x0e2\x17.contracts.ExchangeNameR\vbidExchange\x12\x1b\n" +
	"\task_price\x18\x04 \x01(\x01R\baskPrice\x12\x1b\n" +
	"\tbid_price\x18\x05 \x01(\x01R\bbidPrice\x12\x1d\n" +
	"\n" +
	"profit_abs\x18\x06 \x01(\x01R\tprofitAbs\x12%\n" +
	"\x0eprofit_percent\x18\a \x01(\x01R\rprofitPercent\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe9\x01\n" +
	"\n" +
	"RecentDeal\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12!\n" +
	"\fbuy_exchange\x18\x02 \x01(\tR\vbuyExchange\x12#\n" +
	"\rsell_exchange\x18\x03 \x01(\tR\fsellExchange\x12%\n" +
	"\x0eprofit_percent\x18\x04 \x01(\x01R\rprofitPercent\x12\x1d\n" +
	"\n" +
	"earned_usd\x18\x05 \x01(\x01R\tearnedUsd\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb2\x01\n" +
	"\tDealStats\x12'\n" +
	"\x0fcurrent_balance\x18\x01 \x01(\x01R\x0ecurrentBalance\x12!\n" +
	"\ftotal_earned\x18\x02 \x01(\x01R\vtotalEarned\x12\x1f\n" +
	"\vdeals_count\x18\x03 \x01(\x03R\n" +
	"dealsCount\x128\n" +
	"\frecent_deals\x18\x04 \x03(\v2\x15.contracts.RecentDealR\vrecentDeals*K\n" +
	"\bCoinName\x12\x14\n" +
	"\x10COIN_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCOIN_BTC\x10\x01\x12\f\n" +
	"\bCOIN_ETH\x10\x02\x12\r\n" +
	"\tCOIN_XAUT\x10\x03*\x92\x01\n" +
	"\fExchangeName\x12\x18\n" +
	"\x14EXCHANGE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10EXCHANGE_BINANCE\x10\x01\x12\x13\n" +
	"\x0fEXCHANGE_BITGET\x10\x02\x12\x12\n" +
	"\x0eEXCHANGE_BYBIT\x10\x03\x12\x10\n" +
	"\fEXCHANGE_OKX\x10\x05\"\x04\b\x04\x10\x04*\x11EXCHANGE_COINBASE2W\n" +
	"\x0fAnalyzerService\x12D\n" +
	"\rProcessPrices\x12\x1b.contracts.MarketTickerInfo\x1a\x16.google.protobuf.Empty2\x8d\x01\n" +
	"\x0fExecutorService\x12@\n" +
	"\vProcessDeal\x12\x19.contracts.ProfitDealInfo\x1a\x16.google.protobuf.Empty\x128\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x14.contracts.DealStatsB4Z2github.com/fanoxiz/crypto-monitor/contracts/grpcpbb\x06proto3"

var (
	file_contracts_service_proto_rawDescOnce sync.Once
	file_contracts_service_proto_rawDescData []byte
)

func file_contracts_service_proto_rawDescGZIP() []byte {
	file_contracts_service_proto_rawDescOnce.Do(func() {
		file_contracts_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_service_proto_rawDesc), len(file_contracts_service_proto_rawDesc)))
	})
	return file_contracts_service_proto_rawDescData
}

var file_contracts_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_contracts_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_contracts_service_proto_goTypes = []any{
	(CoinName)(0),                 // 0: contracts.CoinName
	(ExchangeName)(0),             // 1: contracts.ExchangeName
	(*BidAsk)(nil),                // 2: contracts.BidAsk
	(*MarketTickerInfo)(nil),      // 3: contracts.MarketTickerInfo
	(*ProfitDealInfo)(nil),        // 4: contracts.ProfitDealInfo
	(*RecentDeal)(nil),            // 5: contracts.RecentDeal
	(*DealStats)(nil),             // 6: contracts.DealStats
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_contracts_service_proto_depIdxs = []int32{
	0,  // 0: contracts.MarketTickerInfo.coin_name:type_name -> contracts.CoinName
	1,  // 1: contracts.MarketTickerInfo.exchange_name:type_name -> contracts.ExchangeName
	2,  // 2: contracts.MarketTickerInfo.price:type_name -> contracts.BidAsk
	0,  // 3: contracts.ProfitDealInfo.coin_name:type_name -> contracts.CoinName
	1,  // 4: contracts.ProfitDealInfo.ask_exchange:type_name -> contracts.ExchangeName
	1,  // 5: contracts.ProfitDealInfo.bid_exchange:type_name -> contracts.ExchangeName
	7,  // 6: contracts.ProfitDealInfo.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 7: contracts.RecentDeal.created_at:type_name -> google.protobuf.Timestamp
	5,  // 8: contracts.DealStats.recent_deals:type_name -> contracts.RecentDeal
	3,  // 9: contracts.AnalyzerService.ProcessPrices:input_type -> contracts.MarketTickerInfo
	4,  // 10: contracts.ExecutorService.ProcessDeal:input_type -> contracts.ProfitDealInfo
	8,  // 11: contracts.ExecutorService.GetStats:input_type -> google.protobuf.Empty
	8,  // 12: contracts.AnalyzerService.ProcessPrices:output_type -> google.protobuf.Empty
	8,  // 13: contracts.ExecutorService.ProcessDeal:output_type -> google.protobuf.Empty
	6,  // 14: contracts.ExecutorService.GetStats:output_type -> contracts.DealStats
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_contracts_service_proto_init() }
func file_contracts_service_proto_init() {
	if File_contracts_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_service_proto_rawDesc), len(file_contracts_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_contracts_service_proto_goTypes,
		DependencyIndexes: file_contracts_service_proto_depIdxs,
		EnumInfos:         file_contracts_service_proto_enumTypes,
		MessageInfos:      file_contracts_service_proto_msgTypes,
	}.Build()
	File_contracts_service_proto = out.File
	file_contracts_service_proto_goTypes = nil
	file_contracts_service_proto_depIdxs = nil
}
